### ISSUE TITLE
AASW18 startup times

### ISSUE THREAD

**Issue by stefano-v** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#11]
- Follow the directions found here: https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager	Displayed com.SE.AASW18/md52a9665d5fae790519f794745dfd6cf28.SplashScreen: +2s199ms (total +30s153ms)
ActivityManager	Displayed com.SE.AASW18/md52a9665d5fae790519f794745dfd6cf28.MainActivity: +1s877ms
```

- After Startup Tracing:

```
ActivityManager	Displayed com.SE.AASW18/md52a9665d5fae790519f794745dfd6cf28.SplashScreen: +2s23ms (total +30s842ms)
ActivityManager	Displayed com.SE.AASW18/md52a9665d5fae790519f794745dfd6cf28.MainActivity: +1s664ms
```

## Any comments / feedback for how we can improve this experience?

Using Visual Studio 16.2.3 the _AndroidEnableProfiledAot_ property in the csproj is always reset to false, eache time I open the project's properties with the visual editor.

## Version Information (`Help -> About Visual Studio -> Copy Information`)

Microsoft Visual Studio Community 2019
Versione 16.2.3
VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Versione 4.8.03752

Edizione installata: Community

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   5.2.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

Markdown Editor   1.12.236
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

Strumenti C#   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti del Servizio app di Azure versione 3.0.0   16.2.290.48383
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di recapito continuo Microsoft per Visual Studio   0.4
Consente di semplificare la configurazione delle pipeline Azure DevOps direttamente dall'IDE di Visual Studio.

Strumenti di Visual Basic   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   16.0.10627.2001
Strumenti TypeScript per Microsoft Visual Studio

Visual F# Tools 10.4 per F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 per F# 4.6

Visual Studio Tools per contenitori   1.0
Visual Studio Tools per contenitori

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VisualSVN   7.1.2
Integration with Subversion version control. For more information about VisualSVN, see the VisualSVN website at https://www.visualsvn.com
Copyright © 2019 VisualSVN Software Ltd. All rights reserved.

VSColorOutput   2.6.5
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

Xamarin   16.2.0.95 (d16-2@37df81894)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
@stefano-v Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
