### ISSUE TITLE
Build Performance, Startup Performance, and App Size in my App "EasyDates"

### ISSUE THREAD

**Issue by CoffeePerry** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#17]
## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:00:03.64 - EasyDates.csproj
Time Elapsed 00:00:43.72 - EasyDates.Android.csproj
```

- After Cold Build Times Changes:

```
Time Elapsed 00:00:02.02 - EasyDates.csproj
Time Elapsed 00:00:37.88 - EasyDates.Android.csproj
```

## Build Performance (Incremental change)

- Before Incremental Build Times Changes:

```
Time Elapsed 00:00:01.61 - EasyDates.csproj
Time Elapsed 00:00:03.51 - EasyDates.Android.csproj
```

- After Incremental Build Times Changes:

```
Time Elapsed 00:00:01.63 - EasyDates.csproj
Time Elapsed 00:00:03.97 - EasyDates.Android.csproj
```

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager: Displayed it.perry.easydates/md5778a8a0757cac0d669c4a829107716c8.MainActivity: +1s299ms
```

- After Startup Tracing:

```
ActivityManager: Displayed it.perry.easydates/md5778a8a0757cac0d669c4a829107716c8.MainActivity: +808ms
```

## Application Size (Download Size)

I've build "armeabi-v7a" and "arm64-v8a" in this unique APK.

- Before Application Size Changes:

```
App download size: 10,7MB
```
I've build "armeabi-v7a" and "arm64-v8a" in this unique APK.

- After Application Size Changes:

```
App download size: 10,3MB - without: <AndroidPackageFormat>aab</AndroidPackageFormat>
App download size: 5,8MB - with: <AndroidPackageFormat>aab</AndroidPackageFormat>
```
~~For me is not possible archive with:
<AndroidPackageFormat>aab</AndroidPackageFormat>
Get error while archive app:
"Archivio Android non valido (nessun file APK)"~~

Now I able to use also "AndroidPackageFormat: aab".
Thanks to: xamarin/xamarin-android#3493 (comment)

## Bonus

**Before** Build Times:
[BEFORE-Cold_Build_Times.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3537307/BEFORE-Cold_Build_Times.txt)
[BEFORE-Incremental_Build_Times.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3537308/BEFORE-Incremental_Build_Times.txt)

**After** Build Times:
[AFTER-Cold_Build_Times.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3537309/AFTER-Cold_Build_Times.txt)
[AFTER-Incremental_Build_Times.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3537310/AFTER-Incremental_Build_Times.txt)

**Before** Application Size:
![BEFORE-Application_Size](https://user-images.githubusercontent.com/39993316/63639049-adcc9680-c68f-11e9-9502-9ea3049d8d50.png)

**After** Application Size:
![AFTER-Application_Size](https://user-images.githubusercontent.com/39993316/63639054-b3c27780-c68f-11e9-9bff-88502503b596.png)

## Any comments / feedback for how we can improve this experience?

~~- I'm really interested about why "AndroidPackageFormat: aab" not working.~~ Resolved
- It's strange, but in this case, **after** incremental builds are **slower** than **before** incremental builds.

## Version Information
Microsoft Visual Studio Community 2019
Versione 16.2.3
VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Versione 4.8.03752

Edizione installata: Community

Visual C++ 2019   00435-60000-00000-AA136
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   5.2.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Strumenti C#   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti del Servizio app di Azure versione 3.0.0   16.2.290.48383
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Visual Basic   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   16.0.10627.2001
Strumenti TypeScript per Microsoft Visual Studio

Visual C++ per lo sviluppo di applicazioni Linux   1.0.9.29110
Visual C++ per lo sviluppo di applicazioni Linux

Visual F# Tools 10.4 per F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 per F# 4.6

Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake

Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.95 (d16-2@37df81894)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
@CoffeePerry Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
