### ISSUE TITLE
Build Performance, Startup Performance, and App Size

### ISSUE THREAD

**Issue by drjaydenm** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#21]
## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:00:18.98
```

- After Cold Build Times Changes:

```
Time Elapsed 00:00:17.49
```

## Build Performance (Incremental change)

- Before Incremental Build Times Changes:

```
Time Elapsed 00:00:06.31
```

- After Incremental Build Times Changes:

```
Time Elapsed 00:00:05.99
```

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
08-25 19:17:07.782  1841  1865 I ActivityManager: Displayed com.company.xamground/md504bfd7a5b8ac03ea14ba3b2779b4438c.MainActivity: +1s74ms (total +2s719ms)
```

- After Startup Tracing:

```
08-25 19:19:28.941  1841  1865 I ActivityManager: Displayed com.company.xamground/md504bfd7a5b8ac03ea14ba3b2779b4438c.MainActivity: +1s16ms (total +2s738ms)
```

## Application Size (Download Size)

- Before Application Size Changes:

```
App download size: 12.1MB
```

- After Application Size Changes:

```
App download size: 11.5MB
```

## Bonus

- Include a [Diagnostic MSBuild Log File](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or [MSBuild BinLog File](http://msbuildlog.com/)

## Any comments / feedback for how we can improve this experience?
Great to see a real reduction in app startup times and incremental dev build times, this would make a much bigger difference in a bigger app for sure

## Version Information (`Help -> About Visual Studio -> Copy Information`)
Visual Studio Community 2019 for Mac
Version 8.2 (build 1105)
Installation UUID: acc06cd4-b4db-4edd-9abf-cf6fffa14f6d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

Mono Framework MDK
Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.2.3
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.2.105
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.3 (14492.2)
Build 10G8

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

Xamarin.Android
Version: 9.4.0.51 (Visual Studio Community)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/user/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Microsoft Mobile OpenJDK
Java SDK: /Users/user/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Xamarin Designer
Version: 16.2.0.354
Hash: 5f80a14f8
Branch: remotes/origin/d16-2
Build date: 2019-07-11 17:28:26 UTC

Build Information
Release ID: 802001105
Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
Build date: 2019-07-22 18:20:10+00
Build branch: release-8.2
Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Enabled user installed extensions
Xamarin.HotReload 1.0.0.2878453

**Comment by JonDouglas** [comment]
@drjaydenm Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
