### ISSUE TITLE
Build Performance, Startup Performance, and App Size

### ISSUE THREAD

**Issue by CoffeePerry** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#23]
## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:00:01.26 - Xamarin.Forms part
Time Elapsed 00:00:25.10 - Xamarin.Android part
```

- After Cold Build Times Changes:

```
Time Elapsed 00:00:01.19 - Xamarin.Forms part
Time Elapsed 00:00:22.64 - Xamarin.Android part
```

## Build Performance (Incremental change)

- Before Incremental Build Times Changes:

```
Time Elapsed 00:00:00.29 - Xamarin.Forms part
Time Elapsed 00:00:04.44 - Xamarin.Android part
```

- After Incremental Build Times Changes:

```
Time Elapsed 00:00:00.29 - Xamarin.Forms part
Time Elapsed 00:00:04.43 - Xamarin.Android part
```

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
08-26 14:50:20.221	HUAWEI FRD-L09	Info	1205	ActivityManager	Displayed SplashActivity: 0 (total +522ms)
08-26 14:50:21.617	HUAWEI FRD-L09	Info	1205	ActivityManager	Displayed MainActivity: +1s406ms
```

- After Startup Tracing:

```
08-26 14:58:53.280	HUAWEI FRD-L09	Info	1205	ActivityManager	Displayed SplashActivity: 0 (total +1s158ms)
08-26 14:58:54.280	HUAWEI FRD-L09	Info	1205	ActivityManager	Displayed MainActivity: +1s277ms
```
(I've notice that with subsequent starts, times improve)

## Application Size (Download Size)

- Before Application Size Changes:

```
App download size: 18.3MB
```

- After Application Size Changes:

```
App download size: 12.6MB
```
This time I was able to use also "AndroidPackageFormat: aab".
Thanks to: https://github.com/xamarin/xamarin-android/issues/3493#issuecomment-523961607

## Any comments / feedback for how we can improve this experience?
Nothing. App download size reduction is really cool.

## Version Information
Microsoft Visual Studio Community 2019
Versione 16.2.3
VisualStudio.16.Release/16.2.3+29215.179
Microsoft .NET Framework
Versione 4.8.03752

Edizione installata: Community

Visual C++ 2019   00435-60000-00000-AA764
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.2.290.48383
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.290.48383
Per altre informazioni, vedere https://www.asp.net/

Azure Functions and Web Jobs Tools   16.2.290.48383
Azure Functions and Web Jobs Tools

Cookiecutter   16.2.19178.1
Fornisce gli strumenti per la ricerca, la creazione di un'istanza e la personalizzazione dei modelli in formato Cookiecutter.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   5.2.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

ILSpy.AddIn   1.0
Integration of the ILSpy Decompiler into Visual Studio.

IncrediBuild Build Acceleration   1.5.0.10
IncrediBuild effectively reduces compilation and development times by up to 90%.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10610.1 Commit Hash:529a87de2769e143655e31ea81795c42e5775ef8
Aggiunge il supporto per sviluppare ed eseguire il debug di app Node.js in Visual Studio

Pacchetto di Microsoft Visual Studio VC   1.0
Pacchetto di Microsoft Visual Studio VC

Pacchetto di Strumenti Application Insights per Visual Studio   9.1.00611.1
Strumenti Application Insights per Visual Studio

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

Procedure guidate di Microsoft Visual C++   1.0
Procedure guidate di Microsoft Visual C++

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.2.19178.1
Fornisce IntelliSense, progetti, modelli, debug, finestre interattive e altri supporti per gli sviluppatori Python.

Python - Supporto Conda   16.2.19178.1
Supporto Conda per progetti Python.

Python - Supporto Django   16.2.19178.1
Fornisce i modelli e l'integrazione per il framework Web Django.

Python - Supporto IronPython   16.2.19178.1
Fornisce i modelli e l'integrazione per i progetti basati su IronPython.

Python - Supporto profilatura   16.2.19178.1
Supporto profilatura per progetti Python.

Python - Supporto progetti VC   16.1.19129.1
Fornisce il supporto per l'avvio dei progetti C++ con il debug Python abilitato.

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

Strumenti C#   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti del Servizio app di Azure versione 3.0.0   16.2.290.48383
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Microsoft Azure   2.9
Strumenti di Microsoft Azure per Microsoft Visual Studio 0x10 - versione 2.9.20626.2

Strumenti di recapito continuo Microsoft per Visual Studio   0.4
Consente di semplificare la configurazione delle pipeline Azure DevOps direttamente dall'IDE di Visual Studio.

Strumenti di Visual Basic   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   16.0.10627.2001
Strumenti TypeScript per Microsoft Visual Studio

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Consente di usare gli strumenti di test di Visual Studio con unit test scritti per Google Test. Le condizioni d'uso e le comunicazioni relative a terze parti sono disponibili nella directory di installazione dell'estensione.

Visual C++ per lo sviluppo di applicazioni Linux   1.0.9.29110
Visual C++ per lo sviluppo di applicazioni Linux

Visual F# Tools 10.4 per F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 per F# 4.6

Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake

Visual Studio Tools per CMake   1.0
Visual Studio Tools per CMake

Visual Studio Tools per contenitori   1.0
Visual Studio Tools per contenitori

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.95 (d16-2@37df81894)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
@CoffeePerry Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
