### ISSUE TITLE
AndroidApp Startup Tracing

### ISSUE THREAD

**Issue by BryanOroxon** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#24]
- Follow the directions found here: https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager: Displayed com.companyname.androidapp.MainActivity: +2s473ms
```

- After Startup Tracing:
```
ActivityManager: Displayed com.companyname.androidapp.MainActivity: +1s415ms
```

## Any comments / feedback for how we can improve this experience?
I try this with my Hisense F23 and work normal but is more faster with the  AndroidEnableProfiledAot property in the csproj, good Job Xamarain android Team.
## Version Information (`Help -> About Visual Studio -> Copy Information`)
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 2.0
VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA811
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

Azure App Service Tools v3.0.0   16.3.205.56800
Azure App Service Tools v3.0.0

C# Tools   3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19381.3+8e8a754ab056dc16f6dda49110fe8729d1bbabc9
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.179 (d16-3@8669bd4)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.122 (remotes/origin/d16-3@a187bbc98)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.536 (069a02b)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.4 (d16-3/a1f7825)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@17ac7dcfc74
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   12.16.1.9 (a12e76f)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JonDouglas** [comment]
@BryanOroxon Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
