### ISSUE TITLE
Toggl - Performance, Startup and App Size Challenge

### ISSUE THREAD

**Issue by heytherewill** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#29]
I've attempted the performance challenge using the [Toggl Android App](https://github.com/toggl/mobileapp)

## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:00:41.91
```

- After Cold Build Times Changes:

```
Time Elapsed 00:00:36.81
```

Nice 👌 
We also noticed a reasonable improvement in our CI build times (~20%), so this part was a success 🎉 

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager: Displayed com.toggl.giskard/md56d31f6f2c59878fdf075cc45b4e7258a.MainTabBarActivity: +2s236ms
```

- After Startup Tracing:

```
ActivityManager: Displayed com.toggl.giskard/md56d31f6f2c59878fdf075cc45b4e7258a.MainTabBarActivity: +2s805ms
```

No difference here :/

## Application Size (Download Size)

- Before Application Size Changes:

```
com.toggl.giskard-arm64-v8a-Signed.apk
App download size: 32MB
```

- After Application Size Changes:

```
com.toggl.giskard-Signed.aab
App download size: 53MB
```

Comparison is not fair since it's looking at a single architecture APK vs a bundle with all of our supported architectures. Looking at the size of each individual architecture folder, tho, it's likely that this will decrease the app size significantly :)

![image](https://user-images.githubusercontent.com/7688727/63899275-a5979280-c9d2-11e9-886e-40b6fbbc8e02.png)

## Any comments / feedback for how we can improve this experience?

The changes can be seen [on this branch](https://github.com/toggl/mobileapp/tree/gotta-go-FASTER), so you guys can double check if the Profiled AOT bits are correct, after all any performance gains are welcome

**Comment by JonDouglas** [comment]
@heytherewill Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
