### ISSUE TITLE
Pokedex App: Build Performance, Startup Performance, and App Size

### ISSUE THREAD

**Issue by icebeam7** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#40]
- Follow the directions found here: https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge

## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:01:52.67
```

- After Cold Build Times Changes:

```
Time Elapsed 00:01:12.68
```

## Build Performance (Incremental change)

- Before Incremental Build Times Changes:

```
Time Elapsed 00:00:04.24
```

- After Incremental Build Times Changes:

```
Time Elapsed 00:00:03.89
```

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager: Displayed com.companyname.pokedex/md5198d80b26f42e9883a66d8b9s9c1cd8b.MainActivity: +5s501ms
```

- After Startup Tracing:

```
ActivityManager: Displayed com.companyname.pokedex/md5198d80b26f42e9883a66d8b9s9c1cd8b.MainActivity: +4s476ms
```

## Application Size (Download Size)

- Before Application Size Changes:

```
App download size: 12.0 MB
```

- After Application Size Changes:

```
App download size: 11.5 MB (r8)
App download size: 11.6 MB (ProGuard)
```

## Bonus

- Include a [Diagnostic MSBuild Log File](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or [MSBuild BinLog File](http://msbuildlog.com/)

[After Cold Build Times Changes Log.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3562765/After.Cold.Build.Times.Changes.Log.txt)

## Any comments / feedback for how we can improve this experience?
It was easy to follow the challenge due to the several blog posts in which this topic was explained. I faced some difficulties testing them on a Samsung Galaxy Tab P5210 device (Android 4.4) but were eventually solved (main problem was related with the V7 Support libraries). For consistency, I also ran the tests on an emulator (Genymotion, [it was even recorded](https://www.youtube.com/watch?v=c3VtfHOODro), again some problems arose -for instance, the Startup test in Release mode, but I know emulator is not ideal for this-). The rest of the tests went fine.

## Version Information (`Help -> About Visual Studio -> Copy Information`)
[VS 2019 Info.txt](https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge/files/3562766/VS.2019.Info.txt)

**Comment by JonDouglas** [comment]
@icebeam7 Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge

**Comment by icebeam7** [comment]
Thank you @JonDouglas ! I'm not sure at all if I checked this message and if I filled out the survey. If I did, just ignore my new request 😅 Thanks!
