### ISSUE TITLE
Build Performance, Startup Performance, and App Size AppTestOnMac

### ISSUE THREAD

**Issue by BryanOroxon** [JonDouglas/AndroidPerformanceAndAppSizeChallenge#44]
- Follow the directions found here: https://github.com/JonDouglas/AndroidPerformanceAndAppSizeChallenge

## Build Performance (No bin/obj)

- Before Cold Build Times Changes:

```
Time Elapsed 00:00:28.75
```

- After Cold Build Times Changes:

```
Time Elapsed 00:00:22.92
```

## Build Performance (Incremental change)

- Before Incremental Build Times Changes:

```
Time Elapsed 00:00:28.38

```

- After Incremental Build Times Changes:

```
Time Elapsed 00:00:22.52

```

## Startup Performance (Activity Displayed)

- Before Startup Tracing:

```
ActivityManager: Displayed com.companyname.apptestonmac/md5952a099f204f4a700afc90cb97868b74.MainActivity: +4s305ms
```

- After Startup Tracing:

```
ActivityManager: Displayed com.companyname.apptestonmac/md5952a099f204f4a700afc90cb97868b74.MainActivity: +1s198ms
```

## Application Size (Download Size)

- Before Application Size Changes:

```
App download size: 12.4MB
```

- After Application Size Changes:

```
App download size: 10.3MB
```

## Bonus

- Include a [Diagnostic MSBuild Log File](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) or [MSBuild BinLog File](http://msbuildlog.com/)

## Any comments / feedback for how we can improve this experience?

This final issues is made from Visual Studio for Mac because I want to know the difference between VS for Windows and VS for Mac.  Make this test in Visual Studio for Windows is more easy than make this test in Visual Studio for Mac, for example for the log of the Android Device I must to open a SDK Command Promp to run the Command "adb logcat" and later, copy the log and search the "Deployed" information in a Visual Studio Code, because the Android Options are Disable in my VS for Mac.

## Version Information (`Help -> About Visual Studio -> Copy Information`)
=== Visual Studio Community 2019 for Mac ===

Version 8.2.5 (build 5)
Installation UUID: 9d7c8b5e-0684-4983-b2fe-79f155c23837
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2 (14490.120)
Build 10E125

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/bryan/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 29.0.1

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/bryan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802050005
Git revision: 94d90d630b6c7876d1d5298730d14ec97bbde3f9
Build date: 2019-08-22 21:31:34+00
Build branch: release-8.2
Xamarin extensions: 1cf04a6621fb6629226ea0285028954d6196e93f

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Fri Nov  2 20:43:16 PDT 2018
    root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

**Comment by JonDouglas** [comment]
@BryanOroxon Thank you so much for your submission! To claim your swag, please fill out this quick survey!

http://aka.ms/androidappchallenge
